# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

before_install:
  - sudo apt-get install etcd
  - sudo service etcd start

install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run --include "layeredconfig/*py" -m unittest2 discover tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coverage run --include "layeredconfig/*py" -m unittest discover tests; fi
after_success:
  - coveralls